M48
; DRILL file {KiCad 9.0.4} date 2025-12-02T01:12:34+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-02T01:12:34+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X116.86Y-93.4
X122.64Y-93.4
T2
X102.0Y-67.0
X102.0Y-98.0
X128.0Y-67.0
X128.0Y-98.0
M30
